#cspell:disable
openapi: 3.1.0
info:
  title: Thrift eCommerce API
  description: |
    This API allows users to buy a variety of products from different vendors as well as
    selling their own products as a vendor.
  version: 0.0.1
servers:
  - url: https://thrift-production.up.railway.app/{basePath}
    variables:
      basePath:
        default: v1
  - url: https://thrift-dev.up.railway.app/{basePath}
    variables:
      basePath:
        default: v1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      summary: Register an account
      description: Creates an account for the user and authenticates the new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              property:
      responses:
        '201':
          description: 'CREATED'
          content:
            application/json:
              schema:
                type: object
                property:
                  token:
                    type: string
                    description: |
                      unique token string used to authenticate the user
                      expires within 30 minutes
  /auth/login:
    post:
      summary: Logs in the user.
      description: |
        Logs in the user with a token if exists. 
        Else login the user with email or phone identification and creates token
        requestBody:
          required: false
          content:
            application/json:
              schema: 
                type: 
                object
  /user:
    post: {}
    get: {}
    patch: {}
    delete: {}
  /user/customer:
    post: {}
    get: {}
    patch: {}
    delete: {}
  /user/customer/shipping-info:
    post: {}
    get: {}
    patch: {}
    delete: {}
  /user/customer/payment-info:
    post: {}
    get: {}
    patch: {}
    delete: {}
  /user/vendor:
    post: {}
    get: {}
    patch: {}
    delete: {}
  /user/vendor/payment-info:
    post: {}
    get: {}
    patch: {}
    delete: {}
  /user/vendor/stores:
    post: {}
    get: {}
    patch: {}
    delete: {}
  /user/vendor/stores/products:
    post: {}
    get: {}
    patch: {}
    delete: {}
