# cspell:disable
name: Thrift-app Testing

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Run SQL script
        run: |
          docker run -e PGPASSWORD=postgres -v ${{ github.workspace }}:/scripts/ --network host postgres psql -h localhost -U postgres -d test -f /scripts/server/src/db/sql-scripts/create-table.sql

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
        env:
          CI: true
          CLOUDINARY_API_KEY: 351181634279959
          CLOUDINARY_API_SECRET: RAweXTe1mYE8xbqAWFUVbbACry4
          CLOUDINARY_CLOUD_NAME: dk6dujsds
          TEST_JWT_LIFETIME: 30m
          JWT_SECRET: MzUzWYYklY9EBRhbTbbzBTZYV211QrB5w//JxdNK3m+SYjVOKCQhH16BESOY5+x6C1kaJAaT2oTz9zuMNfZkiQ==
          PG_URL: 'postgres://postgres:postgres@localhost:5432/test'
          REDIS_URL: rediss://localhost:6379
